import { speakerColor, speakerName } from "@/lib/personas";
import type { PersonaId, SpeakerId } from "@/lib/types";

/** Profile picture for an AI persona. */
export function avatarSrc(id: PersonaId): string {
  return `/avatars/${id}.svg`;
}

/** Round avatar: AI personas get their illustrated portrait, the moderator a stopwatch, the student an initial. `speaking` adds a green ring. */
export function Avatar({
  speaker,
  studentName = "",
  size = 40,
  speaking = false,
}: {
  speaker: SpeakerId;
  studentName?: string;
  size?: number | "fill"; // "fill": take the parent's size (room tiles scale with their container)
  speaking?: boolean;
}) {
  const box = size === "fill" ? { width: "100%", height: "100%" } : { width: size, height: size };
  if (speaker === "mod") {
    // Neutral outlined avatar with a stopwatch glyph (the moderator keeps time), distinct from persona initials.
    return (
      <span
        className="inline-grid shrink-0 place-items-center rounded-full border border-line-2 bg-surface-3 text-fg-2"
        style={{ ...box, boxShadow: speaking ? "0 0 0 2px var(--color-canvas), 0 0 0 4px var(--color-ok)" : undefined }}
        aria-hidden
      >
        <svg width="50%" height="50%" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round">
          <circle cx="12" cy="14" r="7" />
          <path d="M12 14V10.5M10 2h4M12 2v5" />
        </svg>
      </span>
    );
  }
  if (speaker !== "you") {
    // AI personas: illustrated profile picture (public/avatars, generated by scripts/gen-avatars.mts) on their colour.
    return (
      <span
        className="inline-block shrink-0 overflow-hidden rounded-full select-none"
        style={{
          ...box,
          background: speakerColor(speaker),
          boxShadow: speaking ? "0 0 0 2px var(--color-canvas), 0 0 0 4px var(--color-ok)" : undefined,
        }}
        aria-hidden
      >
        {/* eslint-disable-next-line @next/next/no-img-element -- tiny static SVG, no optimisation needed */}
        <img src={avatarSrc(speaker)} alt="" width={size === "fill" ? 96 : size} height={size === "fill" ? 96 : size} draggable={false} className="block size-full" />
      </span>
    );
  }
  const name = speakerName(speaker, studentName);
  const initials = !studentName.trim() ? "You" : name.slice(0, 1).toUpperCase();
  return (
    <span
      className="inline-grid shrink-0 place-items-center rounded-full bg-fg font-medium text-canvas select-none"
      style={{
        ...box,
        // In "fill" mode the nearest @container (the tile) sets the scale.
        fontSize:
          size === "fill"
            ? initials.length > 1
              ? "clamp(12px, 7cqi, 26px)"
              : "clamp(16px, 10cqi, 40px)"
            : Math.max(10, size * (initials.length > 1 ? 0.3 : 0.42)),
        boxShadow: speaking ? "0 0 0 2px var(--color-canvas), 0 0 0 4px var(--color-ok)" : undefined,
      }}
      aria-hidden
    >
      {initials}
    </span>
  );
}

/** Small "AI" label used to mark AI participants everywhere. */
export function AiTag() {
  return (
    <span
      className="ml-1.5 inline-flex items-center rounded border border-line-2 px-1 align-[1px] font-mono text-[10px] leading-[14px] text-fg-2"
      title="This participant is an AI"
    >
      AI
    </span>
  );
}
